# Generated by Django 3.2.4 on 2021-06-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skinshop', '0002_auto_20210620_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
